language: java

jdk:
  - openjdk14
  - openjdk11
  - openjdk8

after_success:
  - chmod -R 777 ./travis/after_success.sh
  - "./travis/after_success.sh"

env:
  global:
    - secure: L3wbbt3V/0e+bnaqtB0bTCy3mlXsDdw1nDGTntP6eq0uWzNpYszaIzW8zXGd+bcks1jcZ9BG9UgdlYbqxIwGI/uObT1Afg0evCvn2STSdAFY5ik7K7dag0z3rRs+8qYFG8pYSQ08N6hijEMkAO83rmBQ62oMTR35GS5VzIN6gVeEmrQooJX+tc20LyB8/Co8r5Ho8LMhFG8WXxu6QxJX/HhonNnx++Yj+xCxoMKv32kdzwLZV3DnYbIxsJr7WN4wY4sG5YAv9/TVJb8c2IZ9zaXVDxpIs/DW2Qkt9eets1VdajKmq347YJskFwRFx/vcl2Pcuaq7/ubI+wdHL7SxO5qrflJ5M2ZQ2PXlIjBM8V1TeU5/BBw8jEY6lPVFl9HWrPfNXMsYFqMpfUjl19rhDMvH6fVo1GJBiYT0+CW9R7vtQgMKa/a9eCF/J4OZRumG6tQGOlpPh223w8rWUZdUPzMIyEq6xtCwqPmpLid6MPZoCSiabjnINNNSL9i700i3MlcwTaAngiMoN+ZZZ1TYTfSGZhBhICUGz7iqzvsYPOetq9zZWUC8cBPARhNux8B6uP1TiwfWNLG1IxW0+14cJitJRgPxKvFQeYpqoq1YI/WLk3RAvHVWgLfrrCETacTamW7pM1ULJxU9c3G4SiIs/eq21I1hY1PlT5NKVK0p9ks=
    - secure: f/Bf0O4LtNOU4SZWbHlcAAMo1Iuile18c9JsYD90tqSAYPctu2cGm+BxVD02Nnh37JEPEPDStJ3LCm0spsFjnnzZp+lxODkf6zC4p27jVlCZRXKpGipsJdl2kuRk/nxtE8uGBDVndllfbdjAw8ESW2Q8QjP2BjFGS894/a8tKvNjtBUyqudAHCOr6M/ByyAmSYIExs3hqcE1N52wSey2ESX6YfyTwe7Wqv0i6fTjrEu+8oDYxfs//m37DSOnLhzKbMcjuQKNl2jFh2lAyMX/V7X8XnkRWW1jHxboCZMwO0HlYS2pjZOVuIPUrr3BzE7LqdyeHYmL0ZOQIFirPjc0g6pdifeo5u10CtrQPrlcsop+YNC4S1MjONL3+il2TxjsJeN1sR3vzuG2fYuW0OYILN1gYH45RpGpOOPv1nGP7ke/6l44SNSIhI5A5NA9G3hgcc9aOBnHsaVTAfoTzBuuxnsy7EHafSwCLrOqjG8mGjMi8P0VjIIH6VlGept1QfCHxtsB8eKwbQTT+6BcVciY9LgMBf+KkKOWUKrHXPo02wFVxVzlECuYIlXr9teakFWU9Z7ceR2xoNMoYAVLScEFr2zvjLOz6qOCeEYyuE65us1d1nedK1xxfwniQmloWPKBOvgK31WQIJqHpE/hHm7WaH476feBhLN76Zrr40yFO0g=
